### ISSUE TITLE
Create URDF for Leobot 2.0

### ISSUE THREAD

**Issue by AndriyPt** [ros-ukraine/leobot#110]
Robot body 2D drawings
Mass of the body is about 10kg.
Wheel will be connected on the bottom of the robot

![image](https://user-images.githubusercontent.com/10820297/39385463-5843c9c4-4a79-11e8-9c7d-30eead3465d4.png)
![image](https://user-images.githubusercontent.com/10820297/39385731-56bf8236-4a7a-11e8-95c7-5290c89d8e41.png)
![image](https://user-images.githubusercontent.com/10820297/39386272-83a49c30-4a7c-11e8-95bf-5b6d285a3977.png)

Specifications of the wheels: 
Number of wheels:4
Diameter of each wheel:100mm
Width of each wheel:50m
Number of Rollers each wheel:9
Number of Plates each wheel:2
Roller Bearing:Ball bearing
Body material:Aluminium alloy
Roller material:PP+PE
Spacer material:Nylon
Length of roller:19mm
Net weight:400g X 4

![image](https://user-images.githubusercontent.com/10820297/39386480-7a61520c-4a7d-11e8-9899-e8c87d829891.png)
![image](https://user-images.githubusercontent.com/10820297/39386503-9a8e90d0-4a7d-11e8-9403-33a4b4ff5a46.png)

**Comment by LyubomyrD** [comment]
@MaxZhaloba I assigned, as we agreed, to help You with this issue

**Comment by MaxZhaloba** [comment]
Thanks :) I've already started reading turtorials and watching a video presentation on this.

If you have this info, feel free to add the requirements for desired look of Leobot 2.0 e.g. size and should it use a 4-wheeled mecanum base? I'll begin with something very simple and improve it as I learn.

**Comment by AndriyPt** [comment]
Link to Tutorials https://github.com/ros-ukraine/leobot/wiki/FAQ#tutorials-on-urdf

**Comment by LyubomyrD** [comment]
@AndriyPt What is the width of aluminum profile?

**Comment by LyubomyrD** [comment]
@ros-ukraine/leobot , please, have a look at the CAD model of the Leobot 2.0 equipped with LIDAR and two cameras
[Leobot.PDF](https://github.com/ros-ukraine/leobot/files/1958838/Leobot.PDF)

**Comment by AndriyPt** [comment]
@LyubomyrD aluminium profile is MS40+ В - 40x40

**Comment by AndriyPt** [comment]
@LyubomyrD this is what I got in my PDF viewer 
![image](https://user-images.githubusercontent.com/10820297/39410095-2ab1f994-4bfb-11e8-969a-0524a9d2576c.png)

**Comment by LyubomyrD** [comment]
@AndriyPt try to use Adobe Reader

**Comment by LyubomyrD** [comment]
This is what I am getting

![leobot](https://user-images.githubusercontent.com/15168192/39410167-4d326f3e-4bfc-11e8-94d6-a1117f9d8bf2.png)

**Comment by LyubomyrD** [comment]
@AndriyPt please, have a look at the model on GrabCAD https://grabcad.com/library/leobot-2-0-1

**Comment by MaxZhaloba** [comment]
@LyubomyrD, I've measured the sizes of the base in PDF file and they appear to be different from the sizes specified by @AndriyPt in drawing above.

Comparison of sizes, in mm:

|Dimension|PDF size|Drawing size|
|-|-|-|
|Base width|460|500|
|Base depth|500|500|
|Base height|260|300|
|Mount height|1430|1450|
|Mount offset|290|290|

Which values should we take?

**Comment by LyubomyrD** [comment]
@MaxZhaloba great that You spotted this out! Thank You.
Let us follow the original drawings of @AndriyPt 

Since we do not use the CAD model of the body at this stage, I think we have to focus on more urgent tasks. I will be able to update the size of the Leobot later.
