### ISSUE TITLE
Create block diagram of robot's electronics

### ISSUE THREAD

**Issue by AndriyPt** [ros-ukraine/leobot#118]

**Comment by vyosypenko** [comment]
![image](https://user-images.githubusercontent.com/7555013/39620820-2489282e-4f95-11e8-993f-771bc9a5ba84.png)

**Comment by vyosypenko** [comment]
file is added to https://github.com/ros-ukraine/leobot/blob/firmware/leobot_hadware/block_diagrams/Power_Diagram.png

**Comment by AndriyPt** [comment]
@nemo8 please do it in separate branch and pull request and place it in https://github.com/ros-ukraine/leobot/tree/kinetic-devel/docs subfolder called `hardware`.

**Comment by AndriyPt** [comment]
documentation on Pull Requests https://help.github.com/articles/creating-a-pull-request/

**Comment by vyosypenko** [comment]
It is not a schematic, it's a device block diagram. Schematic will be added later.

**Comment by vyosypenko** [comment]
renamed name of the issue
