### ISSUE TITLE
Need to update docker container

### ISSUE THREAD

**Issue by vyosypenko** [ros-ukraine/leobot#120]
1. Add line `<run_depend>rosserial_python</run_depend>` to package.xml. 
2. Add parameter "-device=/dev/ttyUSB0" to docker run command line (step 7).

**Comment by AndriyPt** [comment]
@nemo8 you should do it in your PR. Update README file and package.xml file. Since it is needed for your code to work :)

**Comment by vyosypenko** [comment]
Ok. I will do it.
