### ISSUE TITLE
Management Web Site design

### ISSUE THREAD

**Issue by AndriyPt** [ros-ukraine/leobot#4]
Create simple design for web site with left hand side menu
It will contain camera output in the middle and navigation arrows in the bottom with Forward, Back, Left and Right directions.

**Comment by SystemDiagnosticss** [comment]
[LEOBOT] Simple Web GUI.
http://dropmefiles.com/ckVHz - .psd
http://ibb.co/gFCK4b - .jpeg

**Comment by SystemDiagnosticss** [comment]
Завтра залию по інструкції шо ти писав ...

**Comment by SystemDiagnosticss** [comment]
[LEOBOT] Simple Web UI 
http://ibb.co/j7JnqG - .jpeg
http://dropmefiles.com/X8i7B - .psd

**Comment by SystemDiagnosticss** [comment]
Завтра залию, так як ти писав ....

**Comment by AndriyPt** [comment]
:+1:

**Comment by AndriyPt** [comment]
@SystemDiagnosticss було б добре мати той дизайн у папочці design ;)

**Comment by AndriyPt** [comment]
Closed by #17
