### ISSUE TITLE
Update the credits on web page

### ISSUE THREAD

**Issue by MaxZhaloba** [ros-ukraine/leobot#43]
Currently, our web page contains such credit notice

```
LEOBOT©2018 Created by SYSTEMDI 
Developed by Yaryna Demkiv
```

I suggest to update it to include everyone who works on the project :) Here's how I see it

```
LeoBot©2018 Created by ROS Ukraine Community
```
where [ROS Ukraine Community]() links to one of our sites, such as

1. Page with list of LeoBot contributors https://github.com/ros-ukraine/leobot/graphs/contributors
2. ROS Ukraine GitHub page https://github.com/ros-ukraine
3. Facebook page https://www.facebook.com/groups/279366215828155

**Comment by YarynaD** [comment]
@MaxZhaloba  great idea.

**Comment by LyubomyrD** [comment]
@MaxZhaloba +1

**Comment by AndriyPt** [comment]
@MaxZhaloba I guess link it to GitHub https://github.com/ros-ukraine . Maybe later we will come up with official web site :)

**Comment by SystemDiagnosticss** [comment]
@MaxZhaloba +1

**Comment by MaxZhaloba** [comment]
HTML updated in branch F#16_web_server
