### ISSUE TITLE
Add keyboard teleoperation

### ISSUE THREAD

**Issue by AndriyPt** [ros-ukraine/leobot#50]
Use this as an example https://github.com/AndriyPt/ros-navigation-examples/blob/kinetic-devel/moon_control/launch/teleop.launch

**Comment by MaxZhaloba** [comment]
@AndriyPt, I apparently need your help with this issue.

I'm trying to configure this feature in the branch #F50_keyboard_teleop. I'm performing the following:

1. Start the simulation.launch
2. Start the gmapping.launch
3. Keep the command window on top and press the keys around "K" letter.

I expect the robot to move in gazebo simulation, but nothing happens. Can you please advice what I'm doing incorrectly to reach the goal?

**Comment by AndriyPt** [comment]
@MaxZhaloba for teleoperation you only need `Start the simulation.launch` and launch teleoperation node like here https://github.com/AndriyPt/ros-navigation-examples/blob/kinetic-devel/moon_launch/launch/teleop.launch. GMapping is needed for map building for navigation. 
Please have a look on http://wiki.ros.org/twist_mux node and collaborate with @SystemDiagnosticss since he is currently working on joystick teleoperation. I will not be available till Saturday's evening :)
