### ISSUE TITLE
Create simulation for gallery room

### ISSUE THREAD

**Issue by AndriyPt** [ros-ukraine/leobot#7]
Visit any local gallery or take open source pictures.
Build simulation of one of the gallerie's or museum's room.
Useful material http://gazebosim.org/tutorials?tut=building_editor
Place new world here https://github.com/ros-ukraine/leobot/tree/kinetic-devel/leobot_gazebo/worlds

**Comment by SystemDiagnosticss** [comment]
Фотки і план поверху є .. За локацію взяв Львівську картинну галерею, що на вул. Стефаника, 3

**Comment by SystemDiagnosticss** [comment]
Спробую промалювати в Газебо ...
