### ISSUE TITLE
Hide the navigation and address bars (go fullscreen)

### ISSUE THREAD

**Issue by MaxZhaloba** [ros-ukraine/leobot#90]
The web page should occupy full screen size in Chrome, Safari and preferably in Firefox (mobile versions).

iOS Safari and Firefox show 2 additional elements by default: address bar at the top and navigation bar at page bottom.

**Comment by MaxZhaloba** [comment]
@AndriyPt, Is this feature no longer needed in Leobot 2 or are you closing it in favour to issue #104?

**Comment by AndriyPt** [comment]
@MaxZhaloba from what I have seen on demo it was working. So I have closed it.

**Comment by MaxZhaloba** [comment]
@AndriyPt, this might or might not work for us, but just to clarify, the current solution has such limitations:
* Doesn't work on iOS
* Requires a tap to go fullscreen. There's a chance that we might be able to skip it if we implement the approach with VR API (#104).

**Comment by AndriyPt** [comment]
@MaxZhaloba so it is working with limitation which is fine to keep it closed. For new VR application we might need something else. So this issue is closed.
