### ISSUE TITLE
Increase the simulation speed in Gazebo

### ISSUE THREAD

**Issue by MaxZhaloba** [ros-ukraine/leobot#91]
During our test with @SystemDiagnosticss it gave 7 FPS when we just started Gazebo and 4 FPS when we opened the video stream in VR.

**Comment by MaxZhaloba** [comment]
After implementation of #6 Gazebo loads much faster on my PC, but the simulation speed remains the same.

**Comment by LyubomyrD** [comment]
What is You "Real Time Factor" during the simulation in Gazebo?

**Comment by MaxZhaloba** [comment]
Default world: ~0.5-0.6 and ~0.15-0.20 with web server and video streaming
Art Gallery: ~0.4-0.5 and ~0.1 with video

**Comment by LyubomyrD** [comment]
Yep. That is too slow. I have 06-0.7 in art gallery simulation.
I did not pay attention how much I get with web server and video. Can this be solved with software tuning, I wonder.
