### ISSUE TITLE
Missing gmapping.launch in leobot_launch package

### ISSUE THREAD

**Issue by MaxZhaloba** [ros-ukraine/leobot#97]
Readme specifies the following command to launch the gmapping:

```
roslaunch leobot_launch gmapping.launch
```

It's necessary to create a `gmapping.launch` file in `leobot_launch` package.

**Comment by LyubomyrD** [comment]
Please, use the following command for now. Later it will be updated according to the Readme
roslaunch leobot_2dnav gmapping.launch
